/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { ERC20 } from "./ERC20.sol/ERC20";
export { ERC20__factory } from "./factories/ERC20.sol/ERC20__factory";
export type { MyERC20 } from "./ERC20.sol/MyERC20";
export { MyERC20__factory } from "./factories/ERC20.sol/MyERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
